// src/HomePage.svelte
<script lang="ts">
  import type { ProjectDetails } from './lib/projectContext';
  import { setProjectContext } from './lib/projectContext';
  import Login from './Login.svelte';
  import StoreFront from './StoreFront.svelte';

  export interface EnvConfig {
    projectKey?: string;
    clientId?: string;
    clientSecret?: string;
    apiUrl?: string;
    authUrl?: string;
  }

  let { envConfig }: { envConfig: EnvConfig } = $props();

  let projectDetails = $state<ProjectDetails | null>(null);

  function setProjectDetails(details: ProjectDetails) {
    projectDetails = details;
  }

  // Set context reactively when projectDetails changes
  $effect(() => {
    if (projectDetails) {
      setProjectContext(projectDetails);
    }
  });
</script>

{#if projectDetails}
  <StoreFront {projectDetails} />
{:else}
  <Login {setProjectDetails} {envConfig} />
{/if}

// app/HomePage.tsx
'use client';

import App from "./App";
import { useState } from "react";
import { ProjectContext, ProjectDetails } from "./ProjectContext";
import Login from "./Login";
import { MantineProvider } from "@mantine/core";

import '@mantine/core/styles.css';

import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const queryClient = new QueryClient()

export interface EnvConfig {
  projectKey?: string;
  clientId?: string;
  clientSecret?: string;
  apiUrl?: string;
  authUrl?: string;
}

export default function HomePage({ envConfig }: { envConfig: EnvConfig }) {
  const [projectDetails, setProjectDetails] = useState<ProjectDetails | null>(null);

  return (
    <QueryClientProvider client={queryClient}>
      <ProjectContext.Provider value={projectDetails}>
        <MantineProvider>
          <div className="app">
            {projectDetails ? <App /> : <Login setProjectDetails={setProjectDetails} envConfig={envConfig} />}
          </div>
        </MantineProvider>
      </ProjectContext.Provider>
    </QueryClientProvider>
  )
}
